export const seedData = [
  // Dhaka Division Start
  //Dhaka
  { districtId: 1, name_bn: 'খিলক্ষেত', name_en: 'Khilkhet' },
  { districtId: 1, name_bn: 'কাফরুল', name_en: 'Kafrul' },
  { districtId: 1, name_bn: 'ধানমন্ডি', name_en: 'Dhanmondi' },
  { districtId: 1, name_bn: 'মোহাম্মদপুর', name_en: 'Mohammadpur' },
  { districtId: 1, name_bn: 'সূত্রাপুর', name_en: 'Sutrapur' },
  { districtId: 1, name_bn: 'যাত্রাবাড়ী', name_en: 'Jatrabari' },
  {
    districtId: 1,
    name_bn: 'হযরত শাহ্‌জালাল বিমানবন্দর',
    name_en: 'Hazrat Shajalal Airport',
  },
  { districtId: 1, name_bn: 'গুলশান ১', name_en: 'Gulshan 1' },
  { districtId: 1, name_bn: 'গুলশান ২', name_en: 'Gulshan 2' },
  {
    districtId: 1,
    name_bn: 'উত্তরা পশ্চিম থানা',
    name_en: 'Uttara West Police Station',
  },
  { districtId: 1, name_bn: 'মুগদা', name_en: 'Mugda' },
  { districtId: 1, name_bn: 'রূপনগর', name_en: 'Rupnagar' },
  { districtId: 1, name_bn: 'ভাষানটেক', name_en: 'Bhashantek' },
  { districtId: 1, name_bn: 'ভাটারা', name_en: 'Vatara' },
  { districtId: 1, name_bn: 'বনানী', name_en: 'Banani' },
  { districtId: 1, name_bn: 'ওয়ারী', name_en: 'Wari' },
  { districtId: 1, name_bn: 'শাহজাহানপুর', name_en: 'Shajahanpur' },
  { districtId: 1, name_bn: 'শেরেবাংলা নগর', name_en: 'Sher E Bangla' },
  { districtId: 1, name_bn: 'মিরপুর মডেল থানা', name_en: 'Mirpur Model Thana' },
  { districtId: 1, name_bn: 'দারুস সালাম', name_en: 'Darus Salam' },
  { districtId: 1, name_bn: 'দক্ষিণখান', name_en: 'Dakkhinkhan' },
  { districtId: 1, name_bn: 'উত্তরখান', name_en: 'Uttarkhan' },
  { districtId: 1, name_bn: 'তুরাগ থানা', name_en: 'Turag Thana' },
  { districtId: 1, name_bn: 'উত্তরা মডেল থানা', name_en: 'Uttara Model Thana' },
  { districtId: 1, name_bn: 'ক্যান্টনমেন্ট', name_en: 'Cantonment' },
  { districtId: 1, name_bn: 'বাড্ডা', name_en: 'Badda' },
  { districtId: 1, name_bn: 'পল্লবী', name_en: 'Pallabi' },
  { districtId: 1, name_bn: 'শাহআলী থানা', name_en: 'Sha Ali' },
  {
    districtId: 1,
    name_bn: 'তেজঁগাও শিল্পাঞ্চল',
    name_en: 'Tejgoan Industrial Area',
  },
  { districtId: 1, name_bn: 'তেজঁগাও', name_en: 'Tejgoan' },
  { districtId: 1, name_bn: 'রামপুরা', name_en: 'Rampura' },
  { districtId: 1, name_bn: 'সবুজবাগ', name_en: 'Shabujbag' },
  { districtId: 1, name_bn: 'কদমতলী', name_en: 'Kadamtoli' },
  { districtId: 1, name_bn: 'চকবাজার', name_en: 'Chakbazar' },
  { districtId: 1, name_bn: 'কামরাঙ্গীরচর', name_en: 'Kamrangirchar' },
  { districtId: 1, name_bn: 'কোতয়ালী থানা', name_en: 'Kotwali Thana' },
  { districtId: 1, name_bn: 'লালবাগ', name_en: 'Lalbag' },
  { districtId: 1, name_bn: 'কলাবাগান', name_en: 'Kalabagan' },
  { districtId: 1, name_bn: 'শাহবাগ', name_en: 'Shabag' },
  { districtId: 1, name_bn: 'মতিঝিল', name_en: 'Motijheel' },
  { districtId: 1, name_bn: 'খিলগাঁও', name_en: 'Khilgoan' },
  { districtId: 1, name_bn: 'হাজারীবাগ', name_en: 'Hazaribag' },
  { districtId: 1, name_bn: 'রমনা', name_en: 'Ramna' },
  { districtId: 1, name_bn: 'ডেমরা', name_en: 'Demra' },
  { districtId: 1, name_bn: 'বংশাল', name_en: 'Bangshal' },
  { districtId: 1, name_bn: 'পল্টন', name_en: 'Paltan' },
  { districtId: 1, name_bn: 'নিউমার্কেট', name_en: 'New Market' },
  { districtId: 1, name_bn: 'শ্যামপুর', name_en: 'Shampur' },
  { districtId: 1, name_bn: 'গেন্ডারিয়া', name_en: 'Gandaria' },
  { districtId: 1, name_bn: 'আদাবর', name_en: 'Adabar' },
  { districtId: 1, name_bn: 'হাতিরঝিল', name_en: 'Hatirjheel' },
  // Dhaka Sub Area
  { districtId: 1, name_bn: 'ধামরাই', name_en: 'Dhamrai' },
  { districtId: 1, name_bn: 'সাভার', name_en: 'Savar' },
  { districtId: 1, name_bn: 'আশুলিয়া', name_en: 'Ashulia' },
  {
    districtId: 1,
    name_bn: 'দক্ষিণ কেরানীগঞ্জ',
    name_en: 'Dakkhin Keraniganj',
  },
  {
    districtId: 1,
    name_bn: 'কেরানীগঞ্জ মডেল থানা',
    name_en: 'Keraniganj Model Thana',
  },
  { districtId: 1, name_bn: 'নবাবগঞ্জ', name_en: 'Nababganj' },
  { districtId: 1, name_bn: 'দোহার', name_en: 'Dohar' },

  // Gazipur
  { districtId: 2, name_bn: 'শ্রীপুর', name_en: 'Sreepur' },
  { districtId: 2, name_bn: 'গাজীপুর সদর', name_en: 'Gazipur Sadar' },
  { districtId: 2, name_bn: 'কালিয়াকৈর', name_en: 'Kaliakoir' },
  { districtId: 2, name_bn: 'জয়দেবপুর', name_en: 'Joydebpur' },
  { districtId: 2, name_bn: 'কালীগঞ্জ', name_en: 'Kaliganj' },
  { districtId: 2, name_bn: 'কাপাসিয়া', name_en: 'Kapasia' },
  // Gopalganj
  { districtId: 3, name_bn: 'কাশিয়ানী', name_en: 'Kashiani' },
  { districtId: 3, name_bn: 'কোটালিপাড়া', name_en: 'Kotalipara' },
  { districtId: 3, name_bn: 'গোপালগঞ্জ সদর', name_en: 'Gopalganj Sadar' },
  { districtId: 3, name_bn: 'টুঙ্গিপাড়া', name_en: 'Tungipara' },
  { districtId: 3, name_bn: 'মুকসুদপুর', name_en: 'Muksudpur' },
  // Faridpur
  { districtId: 4, name_bn: 'আলফাডাঙ্গা', name_en: 'Alfadanga' },
  { districtId: 4, name_bn: 'চরভদ্রাসন', name_en: 'Char Bhadrasan' },
  { districtId: 4, name_bn: 'নগরকান্দা', name_en: 'Nagarkanda' },
  { districtId: 4, name_bn: 'ফরিদপুর সদর', name_en: 'Faridpur Sadar' },
  { districtId: 4, name_bn: 'বোয়ালমারী', name_en: 'Boalmari' },
  { districtId: 4, name_bn: 'ভাঙ্গা', name_en: 'Bhanga' },
  { districtId: 4, name_bn: 'মধুখালী', name_en: 'Madhukhali' },
  { districtId: 4, name_bn: 'সদরপুর', name_en: 'Sadarpur' },
  { districtId: 4, name_bn: 'সালথা', name_en: 'Saltha' },
  // Kishoreganj
  { districtId: 5, name_bn: 'অষ্টগ্রাম', name_en: 'Austagram' },
  { districtId: 5, name_bn: 'ইটনা', name_en: 'Itna' },
  { districtId: 5, name_bn: 'কটিয়াদি', name_en: 'Katiadi' },
  { districtId: 5, name_bn: 'করিমগঞ্জ', name_en: 'Karimganj' },
  { districtId: 5, name_bn: 'কিশোরগঞ্জ সদর', name_en: 'Kishoreganj Sadar' },
  { districtId: 5, name_bn: 'কুলিয়ারচর', name_en: 'Kuliarchar' },
  { districtId: 5, name_bn: 'তাড়াইল', name_en: 'Tarail' },
  { districtId: 5, name_bn: 'নিকলী', name_en: 'Nikli' },
  { districtId: 5, name_bn: 'পাকুন্দিয়া', name_en: 'Pakundia' },
  { districtId: 5, name_bn: 'বাজিতপুর', name_en: 'Bajitpur' },
  { districtId: 5, name_bn: 'ভৈরব', name_en: 'Bhairab' },
  { districtId: 5, name_bn: 'মিটামইন', name_en: 'Mithamain' },
  { districtId: 5, name_bn: 'হোসেনপুর', name_en: 'Hossainpur' },
  // Madaripur
  { districtId: 6, name_bn: 'কালকিনি', name_en: 'Kalkini' },
  { districtId: 6, name_bn: 'মাদারীপুর সদর', name_en: 'Madaripur Sadar' },
  { districtId: 6, name_bn: 'রাজৈর', name_en: 'Rajoir' },
  { districtId: 6, name_bn: 'শিবচর', name_en: 'Shibchar' },
  { districtId: 6, name_bn: 'ডাসার', name_en: 'Dasar' },
  // Manikganj
  { districtId: 7, name_bn: 'ঘিওর', name_en: 'Ghior' },
  { districtId: 7, name_bn: 'দৌলতপুর', name_en: 'Daulatpur' },
  { districtId: 7, name_bn: 'মানিকগঞ্জ সদর', name_en: 'Manikganj Sadar' },
  { districtId: 7, name_bn: 'শিবালয়', name_en: 'Shibalaya' },
  { districtId: 7, name_bn: 'সাটুরিয়া', name_en: 'Saturia' },
  { districtId: 7, name_bn: 'সিংগাইর', name_en: 'Singair' },
  { districtId: 7, name_bn: 'হরিরামপুর', name_en: 'Harirampur' },
  // Munshiganj
  { districtId: 8, name_bn: 'গজারিয়া', name_en: 'Gazaria' },
  { districtId: 8, name_bn: 'টঙ্গিবাড়ী', name_en: 'Tongibari' },
  { districtId: 8, name_bn: 'মুন্সিগঞ্জ সদর', name_en: 'Munshiganj Sadar' },
  { districtId: 8, name_bn: 'লৌহজং', name_en: 'Lohajang' },
  { districtId: 8, name_bn: 'শ্রীনগর', name_en: 'Sreenagar' },
  { districtId: 8, name_bn: 'সিরাজদিখাঁন', name_en: 'Serajdikhan' },
  // Narayanganj
  { districtId: 9, name_bn: 'নারায়ণগঞ্জ সদর', name_en: 'Narayanganj Sadar' },
  { districtId: 9, name_bn: 'ফতুল্লা', name_en: 'Fatullah' },
  { districtId: 9, name_bn: 'বন্দর', name_en: 'Bandar' },
  { districtId: 9, name_bn: 'সিদ্ধিরগঞ্জ', name_en: 'Siddhirganj' },
  { districtId: 9, name_bn: 'রূপগঞ্জ', name_en: 'Rupganj' },
  { districtId: 9, name_bn: 'আড়াইহাজার', name_en: 'Araihazar' },
  { districtId: 9, name_bn: 'সোনারগাঁও', name_en: 'Sonargaon' },
  //Narsingdi
  {
    districtId: 10,
    name_bn: 'নরসিংদী মডেল থানা',
    name_en: 'Narsingdi Model Thana',
  },
  { districtId: 10, name_bn: 'পলাশ', name_en: 'Palash' },
  { districtId: 10, name_bn: 'মাধবদী', name_en: 'Madhabdi' },
  { districtId: 10, name_bn: 'শিবপুর', name_en: 'Shibpur' },
  { districtId: 10, name_bn: 'মনোহরদী', name_en: 'Monohardi' },
  { districtId: 10, name_bn: 'রায়পুরা', name_en: 'Raipura' },
  { districtId: 10, name_bn: 'বেলাব', name_en: 'Belabo' },
  // Rajbari
  { districtId: 11, name_bn: 'রাজবাড়ী সদর', name_en: 'Rajbari Sadar' },
  { districtId: 11, name_bn: 'গোয়ালন্দ', name_en: 'Goalanda' },
  { districtId: 11, name_bn: 'পাংশা', name_en: 'Pangsha' },
  { districtId: 11, name_bn: 'বালিয়াকান্দি', name_en: 'Baliakandi' },
  { districtId: 11, name_bn: 'কালুখালী', name_en: 'Kalukhali' },
  // Shariatpur
  { districtId: 12, name_bn: 'শরীয়তপুর সদর', name_en: 'Shariatpur Sadar' },
  { districtId: 12, name_bn: 'জাজিরা', name_en: 'Zanjira' },
  { districtId: 12, name_bn: 'নড়িয়া', name_en: 'Naria' },
  { districtId: 12, name_bn: 'সখিপুর', name_en: 'Shakhipur' },
  { districtId: 12, name_bn: 'গোসাইরহাট', name_en: 'Gosairhat' },
  { districtId: 12, name_bn: 'পদ্মা সেতু দক্ষিণ', name_en: 'Bhedarganj' },
  { districtId: 12, name_bn: 'ডামুড্যা', name_en: 'Damudya' },
  { districtId: 12, name_bn: 'ভেদেরগন্জ', name_en: 'Bhedarganj' },
  // Tangail
  { districtId: 13, name_bn: 'টাঙ্গাইল সদর', name_en: 'Tangail Sadar' },
  { districtId: 13, name_bn: 'দেলদুয়ার', name_en: 'Delduar' },
  { districtId: 13, name_bn: 'নাগরপুর', name_en: 'Nagarpur' },
  { districtId: 13, name_bn: 'মির্জাপুর', name_en: 'Mirzapur' },
  { districtId: 13, name_bn: 'বাসাইল', name_en: 'Basail' },
  { districtId: 13, name_bn: 'সখিপুর', name_en: 'Sakhipur' },
  { districtId: 13, name_bn: 'কালিহাতী', name_en: 'Kalihati' },
  { districtId: 13, name_bn: 'ঘাটাইল', name_en: 'Ghatail' },
  { districtId: 13, name_bn: 'মধুপুর', name_en: 'Madhupur' },
  { districtId: 13, name_bn: 'ধনবাড়ী', name_en: 'Dhanbari' },
  { districtId: 13, name_bn: 'গোপালপুর', name_en: 'Gopalpur' },
  { districtId: 13, name_bn: 'ভূয়াপুর', name_en: 'Bhuapur' },
  {
    districtId: 13,
    name_bn: 'বঙ্গবন্ধু সেতু পূর্ব থানা',
    name_en: 'Bangabandhu Setu East Police Station',
  },
  // Dhaka Division End

  // Chittagong Division Start
  // Chittagong Mohanagar
  { districtId: 14, name_bn: 'কোতোয়ালী', name_en: 'Kotwali' },
  { districtId: 14, name_bn: 'বাকলিয়া', name_en: 'Bakalia' },
  { districtId: 14, name_bn: 'চকবাজার', name_en: 'Chawk Bazar' },
  { districtId: 14, name_bn: 'সদরঘাট', name_en: 'Sadarghat' },
  { districtId: 14, name_bn: 'পাঁচলাইশ', name_en: 'Panchlaish' },
  { districtId: 14, name_bn: 'চাঁন্দগাঁও', name_en: 'Chandgaon' },
  { districtId: 14, name_bn: 'বায়েজীদ', name_en: 'Bayazid' },
  { districtId: 14, name_bn: 'খুলশী', name_en: 'Khulshi' },
  { districtId: 14, name_bn: 'ডবলমুরিং', name_en: 'Doublemooring' },
  { districtId: 14, name_bn: 'পাহাড়তলী', name_en: 'Pahartali' },
  { districtId: 14, name_bn: 'হালিশহর', name_en: 'Halishahar' },
  { districtId: 14, name_bn: 'আকবরশাহ', name_en: 'Akbar Shah' },
  { districtId: 14, name_bn: 'বন্দর', name_en: 'Bandar' },
  { districtId: 14, name_bn: 'পতেঙ্গা', name_en: 'Patenga' },
  { districtId: 14, name_bn: 'কর্ণফুলি', name_en: 'Karnafuli' },
  { districtId: 14, name_bn: 'ইপিজেড', name_en: 'EPZ' },
  // Chittagong
  { districtId: 14, name_bn: 'জোরারগঞ্জ', name_en: 'Zorawargonj' },
  { districtId: 14, name_bn: 'মীরসরাই', name_en: 'Mirsharai' },
  { districtId: 14, name_bn: 'সীতাকুন্ড', name_en: 'Sitakund' },
  { districtId: 14, name_bn: 'সন্দ্বীপ', name_en: 'Sandwip' },
  { districtId: 14, name_bn: 'হাটহাজারী', name_en: 'Hathazari' },
  { districtId: 14, name_bn: 'রাউজান', name_en: 'Raozan' },
  { districtId: 14, name_bn: 'রাঙ্গুনিয়া', name_en: 'Rangunia' },
  { districtId: 14, name_bn: 'ভূজপুর', name_en: 'Bhujpur' },
  { districtId: 14, name_bn: 'ফটিকছড়ি', name_en: 'Fatikchhari' },
  { districtId: 14, name_bn: 'পটিয়া', name_en: 'Patiya' },
  { districtId: 14, name_bn: 'বোয়ালখালী', name_en: 'Boalkhali' },
  { districtId: 14, name_bn: 'আনোয়ারা', name_en: 'Anwara' },
  { districtId: 14, name_bn: 'চন্দনাইশ', name_en: 'Chandanaish' },
  { districtId: 14, name_bn: 'বাঁশখালী', name_en: 'Banshkhali' },
  { districtId: 14, name_bn: 'সাতকানিয়া', name_en: 'Satkania' },
  { districtId: 14, name_bn: 'লোহাগাড়া', name_en: 'Lohagara' },
  // Bandarban
  { districtId: 15, name_bn: 'আলীকদম', name_en: 'Alikadam' },
  { districtId: 15, name_bn: 'থানচি', name_en: 'Thanchi' },
  { districtId: 15, name_bn: 'নাইক্ষ্যংছড়ি', name_en: 'Naikhongchhari' },
  { districtId: 15, name_bn: 'বান্দরবান সদর', name_en: 'Bandarban Sadar' },
  { districtId: 15, name_bn: 'রুমা', name_en: 'Ruma' },
  { districtId: 15, name_bn: 'রোয়াংছড়ি', name_en: 'Rowangchhari' },
  { districtId: 15, name_bn: 'লামা', name_en: 'Lama' },
  // Brahmanbaria
  { districtId: 16, name_bn: 'আখাউড়া', name_en: 'Akhaura' },
  { districtId: 16, name_bn: 'আশুগঞ্জ', name_en: 'Ashuganj' },
  { districtId: 16, name_bn: 'কসবা', name_en: 'Kasba' },
  { districtId: 16, name_bn: 'নবীনগর', name_en: 'Nabinagar' },
  { districtId: 16, name_bn: 'নাসিরনগর', name_en: 'Nasirnagar' },
  { districtId: 16, name_bn: 'বাঞ্ছারামপুর', name_en: 'Banchharampur' },
  { districtId: 16, name_bn: 'বিজয়নগর', name_en: 'Bijoynagar' },
  {
    districtId: 16,
    name_bn: 'ব্রাহ্মণবাড়িয়া সদর',
    name_en: 'Brahmanbaria Sadar',
  },
  {
    districtId: 16,
    name_bn: 'সরাইল',
    name_en: 'Sarail',
  },
  // Chandpur
  { districtId: 17, name_bn: 'সদর মডেল', name_en: 'Kachua' },
  { districtId: 17, name_bn: 'ফরিদগঞ্জ', name_en: 'Faridganj' },
  { districtId: 17, name_bn: 'হাজিগঞ্জ', name_en: 'Hobigonj' },
  { districtId: 17, name_bn: 'শাহরাস্তি', name_en: 'Matlab Uttar' },
  { districtId: 17, name_bn: 'মতলব উত্তর', name_en: 'Matlab Dakshin' },
  { districtId: 17, name_bn: 'মতলব দক্ষিণ', name_en: 'Shahrasti' },
  { districtId: 17, name_bn: 'কচুয়া', name_en: 'Haimchar' },
  { districtId: 17, name_bn: 'হাইমচর', name_en: 'Hajiganj' },

  // Comilla
  { districtId: 18, name_bn: 'কোতয়ালী থানা', name_en: 'Kotwali Thana' },
  { districtId: 18, name_bn: 'চৌদ্দগ্রাম', name_en: 'Chauddagram' },
  { districtId: 18, name_bn: 'দেবিদ্বার', name_en: 'Debidwar' },
  { districtId: 18, name_bn: 'হোমনা', name_en: 'Homna' },
  { districtId: 18, name_bn: 'লাকসাম', name_en: 'Laksam' },
  { districtId: 18, name_bn: 'দাউদকান্দি', name_en: 'Daudkandi' },
  { districtId: 18, name_bn: 'বুড়িচং', name_en: 'Burichang' },
  { districtId: 18, name_bn: 'চান্দিনা', name_en: 'Chandina' },
  { districtId: 18, name_bn: 'বরুড়া', name_en: 'Barura' },
  { districtId: 18, name_bn: 'নাঙ্গলকোট', name_en: 'Nangalkot' },
  { districtId: 18, name_bn: 'মুরাদনগর', name_en: 'Muradnagar' },
  { districtId: 18, name_bn: 'ব্রাহ্মণপাড়া', name_en: 'Brahmanpara' },
  { districtId: 18, name_bn: 'মেঘনা', name_en: 'Meghna' },
  { districtId: 18, name_bn: 'মনোহরগঞ্জ', name_en: 'Manoharganj' },
  { districtId: 18, name_bn: 'তিতাস', name_en: 'Titas' },
  { districtId: 18, name_bn: 'সদর দক্ষিণ', name_en: 'Comilla Sadar Dakshin' },
  { districtId: 18, name_bn: 'বাঙ্গরাবাজার', name_en: 'Bangrabazar' },
  { districtId: 18, name_bn: 'লালমাই', name_en: 'Lalmai' },
  // Cox's Bazar
  { districtId: 19, name_bn: 'উখিয়া', name_en: 'Ukhia' },
  { districtId: 19, name_bn: 'কক্সবাজার সদর', name_en: "Cox's Bazar Sadar" },
  { districtId: 19, name_bn: 'কুতুবদিয়া', name_en: 'Kutubdia' },
  { districtId: 19, name_bn: 'চকোরিয়া', name_en: 'Chakaria' },
  { districtId: 19, name_bn: 'টেকনাফ', name_en: 'Teknaf' },
  { districtId: 19, name_bn: 'পেকুয়া', name_en: 'Pekua' },
  { districtId: 19, name_bn: 'মহেশখালী', name_en: 'Maheshkhali' },
  { districtId: 19, name_bn: 'রামু', name_en: 'Ramu' },
  { districtId: 19, name_bn: 'ঈদগাঁও থানা', name_en: 'Eidgah Police Station' },
  // Feni
  { districtId: 20, name_bn: 'ছাগলনাইয়া', name_en: 'Chhagalnaiya' },
  { districtId: 20, name_bn: 'দাগনভূঁইয়া', name_en: 'Daganbhuiyan' },
  { districtId: 20, name_bn: 'পরশুরাম', name_en: 'Parshuram' },
  { districtId: 20, name_bn: 'ফুলগাজী', name_en: 'Fulgazi' },
  { districtId: 20, name_bn: 'ফেনী সদর', name_en: 'Feni Sadar' },
  { districtId: 20, name_bn: 'সোনাগাজী', name_en: 'Sonagazi' },
  // Khagrachhari
  { districtId: 21, name_bn: 'খাগড়াছড়ি সদর', name_en: 'Khagrachhari Sadar' },
  { districtId: 21, name_bn: 'দীঘিনালা', name_en: 'Dighinala' },
  { districtId: 21, name_bn: 'পানছড়ি', name_en: 'Panchhari' },
  { districtId: 21, name_bn: 'মহালছড়ি', name_en: 'Mahalchhari' },
  { districtId: 21, name_bn: 'মাটিরাঙ্গা', name_en: 'Matiranga' },
  { districtId: 21, name_bn: 'মানিকছড়ি', name_en: 'Manikchhari' },
  { districtId: 21, name_bn: 'রামগড়', name_en: 'Ramgarh' },
  { districtId: 21, name_bn: 'লক্ষ্মীছড়ি', name_en: 'Lakshmichhari' },
  // Lakshmipur
  { districtId: 22, name_bn: 'কমলনগর', name_en: 'Kamalnagar' },
  { districtId: 22, name_bn: 'রামগঞ্জ', name_en: 'Ramganj' },
  { districtId: 22, name_bn: 'রামগতি', name_en: 'Ramgati' },
  { districtId: 22, name_bn: 'রায়পুর', name_en: 'Raipur' },
  { districtId: 22, name_bn: 'লক্ষ্মীপুর সদর', name_en: 'Lakshmipur Sadar' },
  { districtId: 22, name_bn: 'চন্দ্রগঞ্জ থানা', name_en: 'Chandragonj Police' },
  // Noakhali
  { districtId: 23, name_bn: 'কবিরহাট', name_en: 'Kabirhat' },
  { districtId: 23, name_bn: 'কোম্পানীগঞ্জ', name_en: 'Companiganj' },
  { districtId: 23, name_bn: 'চাটখিল', name_en: 'Chatkhil' },
  { districtId: 23, name_bn: 'নোয়াখালী সদর', name_en: 'Noakhali Sadar' },
  { districtId: 23, name_bn: 'বেগমগঞ্জ', name_en: 'Begumganj' },
  { districtId: 23, name_bn: 'সেনবাগ', name_en: 'Senbagh' },
  { districtId: 23, name_bn: 'সুবর্ণচর', name_en: 'Subarnachar' },
  { districtId: 23, name_bn: 'সোনাইমুড়ি', name_en: 'Sonaimuri' },
  { districtId: 23, name_bn: 'হাতিয়া', name_en: 'Hatiya' },
  // Rangamati
  { districtId: 24, name_bn: 'কাউখালী', name_en: 'Kawkhali' },
  { districtId: 24, name_bn: 'চন্দ্রঘোনা', name_en: 'Kaptai' },
  { districtId: 24, name_bn: 'কাপ্তাই জুরাছড়ি', name_en: 'Juraichhari' },
  { districtId: 24, name_bn: 'নানিয়ারচর', name_en: 'Naniarchar' },
  { districtId: 24, name_bn: 'বরকল', name_en: 'Barkal' },
  { districtId: 24, name_bn: 'বাঘাইছড়ি', name_en: 'Baghaichhari' },
  { districtId: 24, name_bn: 'সাজেক', name_en: 'Belaichhari' },
  { districtId: 24, name_bn: 'বিলাইছড়ি', name_en: 'Rangamati Sadar' },
  { districtId: 24, name_bn: 'কোতোয়ালী', name_en: 'Rajasthali' },
  { districtId: 24, name_bn: 'রাজস্থলী', name_en: 'Langadu' },
  { districtId: 24, name_bn: 'লংগদু', name_en: 'Langadu' },
  // Chittagong Division End

  // Rajshahi Division Start
  // Rajshahi
  { districtId: 25, name_bn: 'পবা', name_en: 'Paba' },
  { districtId: 25, name_bn: 'চারঘাট', name_en: 'Charghat' },
  { districtId: 25, name_bn: 'বাঘা', name_en: 'Bagha' },
  { districtId: 25, name_bn: 'পুঠিয়া', name_en: 'Puthia' },
  { districtId: 25, name_bn: 'তানোর', name_en: 'Tanore' },
  { districtId: 25, name_bn: 'দূর্গাপুর', name_en: 'Durgapur' },
  { districtId: 25, name_bn: 'মোহনপুর', name_en: 'Mohanpur' },
  { districtId: 25, name_bn: 'বাগমারা', name_en: 'Baghmara' },
  { districtId: 25, name_bn: 'গোদাগাড়ী', name_en: 'Godagari' },
  // Natore
  { districtId: 26, name_bn: 'নাটোর সদর', name_en: 'Natore Sadar' },
  { districtId: 26, name_bn: 'লালপুর', name_en: 'Lalpur' },
  { districtId: 26, name_bn: 'বাগাতিপাড়া', name_en: 'Bagatipara' },
  { districtId: 26, name_bn: 'বড়াইগ্রাম', name_en: 'Baraigram' },
  { districtId: 26, name_bn: 'গুরুদাসপুর', name_en: 'Gurudaspur' },
  { districtId: 26, name_bn: 'সিংড়া', name_en: 'Singra' },
  { districtId: 26, name_bn: 'নলডাঙ্গা', name_en: 'Naldanga' },
  // Naogaon
  { districtId: 27, name_bn: 'নওগাঁ সদর', name_en: 'Naogaon Sadar' },
  { districtId: 27, name_bn: 'আত্রাই', name_en: 'Atrai' },
  { districtId: 27, name_bn: 'রাণীনগর', name_en: 'Raninagar' },
  { districtId: 27, name_bn: 'পত্নীতলা', name_en: 'Patnitala' },
  { districtId: 27, name_bn: 'সাপাহার', name_en: 'Sapahar' },
  { districtId: 27, name_bn: 'পোরশা', name_en: 'Porsha' },
  { districtId: 27, name_bn: 'মান্দা', name_en: 'Manda' },
  { districtId: 27, name_bn: 'মহাদেবপুর', name_en: 'Mahadebpur' },
  { districtId: 27, name_bn: 'ধামইরহাট', name_en: 'Dhamoirhat' },
  { districtId: 27, name_bn: 'বদলগাছী', name_en: 'Badalgachhi' },
  { districtId: 27, name_bn: 'নিয়ামতপুর', name_en: 'Niamatpur' },
  // Chapai Nawabganj
  {
    districtId: 28,
    name_bn: 'চাঁপাইনবাবগঞ্জ সদর',
    name_en: 'C. Nawabganj Sadar',
  },
  { districtId: 28, name_bn: 'শিবগঞ্জ', name_en: 'Shibganj' },
  { districtId: 28, name_bn: 'ভোলাহাট', name_en: 'Bholahat' },
  { districtId: 28, name_bn: 'গোমস্তাপুর', name_en: 'Gomastapur' },
  { districtId: 28, name_bn: 'নাচোল', name_en: 'Nachole' },
  // Bogra
  { districtId: 29, name_bn: 'বগুড়া সদর', name_en: 'Bogra Sadar' },
  { districtId: 29, name_bn: 'শাজাহানপুর', name_en: 'Shahjahanpur' },
  { districtId: 29, name_bn: 'শেরপুর', name_en: 'Sherpur' },
  { districtId: 29, name_bn: 'ধুনট', name_en: 'Dhunat' },
  { districtId: 29, name_bn: 'সারিয়াকান্দি', name_en: 'Sariakandi' },
  { districtId: 29, name_bn: 'গাবতলী', name_en: 'Gabtali' },
  { districtId: 29, name_bn: 'সোনাতলা', name_en: 'Sonatala' },
  { districtId: 29, name_bn: 'শিবগঞ্জ', name_en: 'Shibganj' },
  { districtId: 29, name_bn: 'দুপচাচিয়া', name_en: 'Dhupchanchia' },
  { districtId: 29, name_bn: 'কাহালু', name_en: 'Kahaloo' },
  { districtId: 29, name_bn: 'আদমদীঘি', name_en: 'Adamdighi' },
  { districtId: 29, name_bn: 'নন্দীগ্রাম', name_en: 'Nandigram' },
  // Joypurhat
  { districtId: 30, name_bn: 'জয়পুরহাট সদর', name_en: 'Joypurhat Sadar' },
  { districtId: 30, name_bn: 'পাঁচবিবি', name_en: 'Panchbibi' },
  { districtId: 30, name_bn: 'আক্কেলপুর', name_en: 'Akkelpur' },
  { districtId: 30, name_bn: 'ক্ষেতলাল', name_en: 'Khetlal' },
  { districtId: 30, name_bn: 'কালাই', name_en: 'Kalai' },
  // Pabna
  { districtId: 31, name_bn: 'পাবনা সদর', name_en: 'Pabna Sadar' },
  { districtId: 31, name_bn: 'সাঁথিয়া', name_en: 'Santhia' },
  { districtId: 31, name_bn: 'সুজানগর', name_en: 'Sujanagar' },
  { districtId: 31, name_bn: 'বেড়া', name_en: 'Bera' },
  { districtId: 31, name_bn: 'ঈশ্বরদী', name_en: 'Ishwardi' },
  { districtId: 31, name_bn: 'ভাঙ্গুড়া', name_en: 'Bhangura' },
  { districtId: 31, name_bn: 'ফরিদপুর', name_en: 'Faridpur' },
  { districtId: 31, name_bn: 'চাটমোহর', name_en: 'Chatmohar' },
  { districtId: 31, name_bn: 'আর্টঘড়িয়া', name_en: 'Atgharia' },
  // Sirajganj
  { districtId: 32, name_bn: 'সিরাজগঞ্জ সদর', name_en: 'Sirajganj Sadar' },
  { districtId: 32, name_bn: 'রায়গঞ্জ', name_en: 'Raiganj' },
  { districtId: 32, name_bn: 'কাজিপুর', name_en: 'Kazipur' },
  { districtId: 32, name_bn: 'তাড়াশ', name_en: 'Tarash' },
  { districtId: 32, name_bn: 'শাহজাদপুর', name_en: 'Shahjadpur' },
  { districtId: 32, name_bn: 'উল্লাপাড়া', name_en: 'Ullahpara' },
  { districtId: 32, name_bn: 'কামারখন্দ', name_en: 'Kamarkhanda' },
  { districtId: 32, name_bn: 'বেলকুচি', name_en: 'Belkuchi' },
  { districtId: 32, name_bn: 'চৌহালী', name_en: 'Chauhali' },
  // Rajshahi Division End

  // Khulna Division Start
  // Khulna Mohanagar
  { districtId: 33, name_bn: 'খুলনা সদর', name_en: 'Khulna Sadar' },
  { districtId: 33, name_bn: 'সোনাডাঙ্গা', name_en: 'Sonadanga' },
  { districtId: 33, name_bn: 'দৌলতপুর', name_en: 'Daulatpur' },
  { districtId: 33, name_bn: 'খালিশপুর', name_en: 'Khalishpur' },
  { districtId: 33, name_bn: 'খানজাহান আলী', name_en: 'Khan Jahan Ali' },
  { districtId: 33, name_bn: 'আড়ংঘাটা', name_en: 'Arongghata' },
  { districtId: 33, name_bn: 'লবনচরা', name_en: 'Lobonchora' },
  { districtId: 33, name_bn: 'হরিনটানা', name_en: 'Horintana' },
  // Khulna
  { districtId: 33, name_bn: 'রূপসা', name_en: 'Rupsa' },
  { districtId: 33, name_bn: 'বটিয়াঘাটা', name_en: 'Batiaghata' },
  { districtId: 33, name_bn: 'দিঘলিয়া', name_en: 'Dighalia' },
  { districtId: 33, name_bn: 'ফুলতলা', name_en: 'Phultala' },
  { districtId: 33, name_bn: 'ডুমুরিয়া', name_en: 'Dumuria' },
  { districtId: 33, name_bn: 'তেরখাদা', name_en: 'Terokhada' },
  { districtId: 33, name_bn: 'দাকোপ', name_en: 'Dacope' },
  { districtId: 33, name_bn: 'কয়রা', name_en: 'Koyra' },
  { districtId: 33, name_bn: 'পাইকগাছা', name_en: 'Paikgachha' },
  // Bagerhat
  { districtId: 34, name_bn: 'কচুয়া', name_en: 'Kachua' },
  { districtId: 34, name_bn: 'চিতলমারী', name_en: 'Chitalmari' },
  { districtId: 34, name_bn: 'ফকিরহাট', name_en: 'Fakirhat' },
  { districtId: 34, name_bn: 'বাগেরহাট সদর', name_en: 'Bagerhat Sadar' },
  { districtId: 34, name_bn: 'মংলা', name_en: 'Mongla' },
  { districtId: 34, name_bn: 'মোড়েলগঞ্জ', name_en: 'Morrelganj' },
  { districtId: 34, name_bn: 'মোল্লাহাট', name_en: 'Mollahat' },
  { districtId: 34, name_bn: 'রামপাল', name_en: 'Rampal' },
  { districtId: 34, name_bn: 'শরণখোলা', name_en: 'Sarankhola' },
  // Chuadanga
  { districtId: 35, name_bn: 'চুয়াডাঙ্গা সদর', name_en: 'Chuadanga Sadar' },
  { districtId: 35, name_bn: 'আলমডাঙ্গা', name_en: 'Alamdanga' },
  { districtId: 35, name_bn: 'জীবননগর', name_en: 'Jiban Nagar' },
  { districtId: 35, name_bn: 'দামুড়হুদা', name_en: 'Damurhuda' },
  { districtId: 35, name_bn: 'দর্শনা', name_en: 'Darshana' },
  // Jessore
  { districtId: 36, name_bn: 'যশোর সদর', name_en: 'Jessore Sadar' },
  { districtId: 36, name_bn: 'চৌগাছা থানা', name_en: 'Chaugachha' },
  { districtId: 36, name_bn: 'অভয়নগর থানা', name_en: 'Abhaynagar' },
  { districtId: 36, name_bn: 'বাঘারপাড়া থানা', name_en: 'Bagherpara' },
  { districtId: 36, name_bn: 'মণিরামপুর থানা', name_en: 'Manirampur' },
  { districtId: 36, name_bn: 'কেশবপুর থানা', name_en: 'Keshabpur' },
  { districtId: 36, name_bn: 'ঝিকরগাছা থানা', name_en: 'Jhikargachha' },
  { districtId: 36, name_bn: 'শার্শা থানা', name_en: 'Sharsha' },
  { districtId: 36, name_bn: 'বেনাপোল পোর্ট', name_en: 'Benapole Port' },
  // Jhenaidah
  { districtId: 37, name_bn: 'ঝিনাইদহ সদর', name_en: 'Jhenaidah Sadar' },
  { districtId: 37, name_bn: 'কালীগঞ্জ', name_en: 'Kaliganj' },
  { districtId: 37, name_bn: 'শৈলকুপা', name_en: 'Shailkupa' },
  { districtId: 37, name_bn: 'হরিণাকুন্‌ডু', name_en: 'Harinakunda' },
  { districtId: 37, name_bn: 'কোটচাঁদপুর', name_en: 'Kotchandpur' },
  { districtId: 37, name_bn: 'মহেশপুর', name_en: 'Maheshpur' },

  // Kushtia
  { districtId: 38, name_bn: 'কুষ্টিয়া সদর', name_en: 'Kustia Sadar' },
  { districtId: 38, name_bn: 'কুমারখালী', name_en: 'Kumarkhali' },
  { districtId: 38, name_bn: 'মিরপুর', name_en: 'Mirpur' },
  { districtId: 38, name_bn: 'ভেড়ামারা', name_en: 'Bheramara' },
  { districtId: 38, name_bn: 'খোকসা', name_en: 'Khoksa' },
  { districtId: 38, name_bn: 'দৌলতপুর', name_en: 'Daulatpur' },
  {
    districtId: 38,
    name_bn: 'ইসলাম বিশ্ববিদ্যালয়',
    name_en: 'Islamic University',
  },
  // Magura
  { districtId: 39, name_bn: 'মাগুরা সদর', name_en: 'Magura Sadar' },
  { districtId: 39, name_bn: 'মহম্মদপুর', name_en: 'Mohammadpur' },
  { districtId: 39, name_bn: 'শালিখা', name_en: 'Shalikha' },
  { districtId: 39, name_bn: 'শ্রীপুর', name_en: 'Sreepur' },
  // Meherpur
  { districtId: 40, name_bn: 'মেহেরপুর সদর', name_en: 'Meherpur Sadar' },
  { districtId: 40, name_bn: 'গাংনী', name_en: 'Gangni' },
  { districtId: 40, name_bn: 'মুজিবনগর', name_en: 'Mujibnagar' },
  // Narail
  { districtId: 41, name_bn: 'নড়াইল সদর', name_en: 'Narail Sadar' },
  { districtId: 41, name_bn: 'লোহাগড়া', name_en: 'Lohagara' },
  { districtId: 41, name_bn: 'কালিয়া', name_en: 'Kalia' },
  { districtId: 41, name_bn: 'নড়াগাতী', name_en: 'Noragati' },
  // Satkhira
  { districtId: 42, name_bn: 'সাতক্ষীরা সদর', name_en: 'Satkhira Sadar' },
  { districtId: 42, name_bn: 'কলারোয়া', name_en: 'Kalaroa' },
  { districtId: 42, name_bn: 'তালা', name_en: 'Tala' },
  { districtId: 42, name_bn: 'পাটকেলঘাটা', name_en: 'Patkelghata' },
  { districtId: 42, name_bn: 'কালিগঞ্জ', name_en: 'Kaliganj' },
  { districtId: 42, name_bn: 'দেবহাটা', name_en: 'Debhata' },
  { districtId: 42, name_bn: 'আশাশুনি', name_en: 'Assasuni' },
  { districtId: 42, name_bn: 'শ্যামনগর', name_en: 'Shyamnagar' },
  // Khulna Division End

  // Barisal Division Start
  // Barisal
  { districtId: 43, name_bn: 'এয়ারপোর্ট', name_en: 'Airport' },
  { districtId: 43, name_bn: 'কাউনিয়া', name_en: 'Kaonia' },
  { districtId: 43, name_bn: 'কোতোয়ালি', name_en: 'Kotwali' },
  { districtId: 43, name_bn: 'বন্দর', name_en: 'Bandar' },
  { districtId: 43, name_bn: 'আগৈলঝরা', name_en: 'Agailjhara' },
  { districtId: 43, name_bn: 'উজিরপুর', name_en: 'Wazirpur' },
  { districtId: 43, name_bn: 'গৌরনদী', name_en: 'Gaurnadi' },
  { districtId: 43, name_bn: 'বরিশাল সদর', name_en: 'Barisal Sadar' },
  { districtId: 43, name_bn: 'বাকেরগঞ্জ', name_en: 'Bakerganj' },
  { districtId: 43, name_bn: 'বানারীপাড়া', name_en: 'Banaripara' },
  { districtId: 43, name_bn: 'বাবুগঞ্জ', name_en: 'Babuganj' },
  { districtId: 43, name_bn: 'মুলাদি', name_en: 'Muladi' },
  { districtId: 43, name_bn: 'মেহেন্দীগঞ্জ', name_en: 'Mehendiganj' },
  { districtId: 43, name_bn: 'হিজলা', name_en: 'Hizla' },
  // Barguna
  { districtId: 44, name_bn: 'বরগুনা থানা', name_en: 'Barguna' },
  { districtId: 44, name_bn: 'তালতলী থানা', name_en: 'Taltoli' },
  { districtId: 44, name_bn: 'আমতলী থানা', name_en: 'Amtali' },
  { districtId: 44, name_bn: 'বামনা থানা', name_en: 'Bamna' },
  { districtId: 44, name_bn: 'বেতাগী থানা', name_en: 'Betagi' },
  { districtId: 44, name_bn: 'পাথরঘাটা থানা', name_en: 'Patharghata' },
  // Bhola
  { districtId: 45, name_bn: 'ভোলা সদর', name_en: 'Bhola Sadar' },
  { districtId: 45, name_bn: 'দৌলতখান', name_en: 'Daulat Khan' },
  { districtId: 45, name_bn: 'লালমোহন', name_en: 'Lalmohan' },
  { districtId: 45, name_bn: 'বোরহানউদ্দিন', name_en: 'Burhanuddin' },
  { districtId: 45, name_bn: 'তজুমদ্দিন', name_en: 'Tazumuddin' },
  { districtId: 45, name_bn: 'মনপুরা', name_en: 'Manpura' },
  { districtId: 45, name_bn: 'শশীভূষণ', name_en: 'Shashibhusan' },
  { districtId: 45, name_bn: 'চরফ্যাসন', name_en: 'Char Fasson' },
  { districtId: 45, name_bn: 'দুলারহাট', name_en: 'Dularhat' },
  { districtId: 45, name_bn: 'দক্ষিন আইচা', name_en: 'Dakshin Aicha' },
  // Jhalokati
  { districtId: 46, name_bn: 'কাঁঠালিয়া', name_en: 'Kathalia' },
  { districtId: 46, name_bn: 'ঝালকাঠি সদর', name_en: 'Jhalokati Sadar' },
  { districtId: 46, name_bn: 'নলছিটি', name_en: 'Nalchity' },
  { districtId: 46, name_bn: 'রাজাপুর', name_en: 'Rajapur' },
  // Patuakhali
  { districtId: 47, name_bn: 'কলাপাড়া', name_en: 'Kalapara' },
  { districtId: 47, name_bn: 'গলাচিপা', name_en: 'Galachipa' },
  { districtId: 47, name_bn: 'দশমিনা', name_en: 'Dashmina' },
  { districtId: 47, name_bn: 'দুমকি', name_en: 'Dumki' },
  { districtId: 47, name_bn: 'পটুয়াখালী সদর', name_en: 'Patuakhali Sadar' },
  { districtId: 47, name_bn: 'বাউফল', name_en: 'Bauphal' },
  { districtId: 47, name_bn: 'মির্জাগঞ্জ', name_en: 'Mirzaganj' },
  { districtId: 47, name_bn: 'রাঙ্গাবালী', name_en: 'Rangabali' },
  { districtId: 47, name_bn: 'মহিপুর', name_en: 'Mahipur' },
  // Pirojpur
  { districtId: 48, name_bn: 'কাউখালী', name_en: 'Kawkhali' },
  { districtId: 48, name_bn: 'জিয়ানগর', name_en: 'Zianagar' },
  { districtId: 48, name_bn: 'নাজিরপুর', name_en: 'Nazirpur' },
  { districtId: 48, name_bn: 'নেছারাবাদ', name_en: 'Nesarabad' },
  { districtId: 48, name_bn: 'পিরোজপুর সদর', name_en: 'Pirojpur Sadar' },
  { districtId: 48, name_bn: 'ভান্ডারিয়া', name_en: 'Bhandaria' },
  { districtId: 48, name_bn: 'মঠবাড়ীয়া', name_en: 'Mathbaria' },
  // Barisal Division End

  // Sylhet Division Start
  // Habiganj
  { districtId: 49, name_bn: 'আজমিরিগঞ্জ', name_en: 'Ajmiriganj' },
  { districtId: 49, name_bn: 'চুনারুঘাট', name_en: 'Chunarughat' },
  { districtId: 49, name_bn: 'নবীগঞ্জ', name_en: 'Nabiganj' },
  { districtId: 49, name_bn: 'বানিয়াচং', name_en: 'Baniachong' },
  { districtId: 49, name_bn: 'বাহুবল', name_en: 'Bahubal' },
  { districtId: 49, name_bn: 'মাধবপুর', name_en: 'Madhabpur' },
  { districtId: 49, name_bn: 'লাখাই', name_en: 'Lakhai' },
  { districtId: 49, name_bn: 'হবিগঞ্জ সদর', name_en: 'Habiganj Sadar' },
  // Moulvibazar
  { districtId: 50, name_bn: 'কমলগঞ্জ', name_en: 'Kamalganj' },
  { districtId: 50, name_bn: 'কুলাউড়া', name_en: 'Kulaura' },
  { districtId: 50, name_bn: 'জুড়ী', name_en: 'Juri' },
  { districtId: 50, name_bn: 'মৌলভীবাজার সদর', name_en: 'Maulvibazar Sadar' },
  { districtId: 50, name_bn: 'বড়লেখা', name_en: 'Barlekha' },
  { districtId: 50, name_bn: 'রাজনগর', name_en: 'Rajnagar' },
  { districtId: 50, name_bn: 'শ্রীমঙ্গল', name_en: 'Sreemangal' },
  // Sunamganj
  { districtId: 51, name_bn: 'ছাতক', name_en: 'Chhatak' },
  { districtId: 51, name_bn: 'জগন্নাথপুর', name_en: 'Jagannathpur' },
  { districtId: 51, name_bn: 'জামালগঞ্জ', name_en: 'Jamalganj' },
  { districtId: 51, name_bn: 'তাহিরপুর', name_en: 'Tahirpur' },
  { districtId: 51, name_bn: 'দক্ষিণ সুনামগঞ্জ', name_en: 'Dakshin Sunamganj' },
  { districtId: 51, name_bn: 'দিরাই', name_en: 'Derai' },
  { districtId: 51, name_bn: 'দোয়ারাবাজার', name_en: 'Dowarabazar' },
  { districtId: 51, name_bn: 'ধর্মপাশা', name_en: 'Dharampasha' },
  { districtId: 51, name_bn: 'বিশ্বম্ভরপুর', name_en: 'Bishwambarpur' },
  { districtId: 51, name_bn: 'সাল্লা', name_en: 'Sulla' },
  { districtId: 51, name_bn: 'সুনামগঞ্জ সদর', name_en: 'Sunamganj Sadar' },
  // Sylhet
  { districtId: 52, name_bn: 'সিলেট সদর', name_en: 'Sylhet Sadar' },
  { districtId: 52, name_bn: 'বিমানবন্দর', name_en: 'Bimanbandar' },
  { districtId: 52, name_bn: 'কোতোয়ালী', name_en: 'Kotwali' },
  { districtId: 52, name_bn: 'জালালাবাদ', name_en: 'Jalalabad' },
  { districtId: 52, name_bn: 'দক্ষিণ সুরমা', name_en: 'Dakshin Surma' },
  { districtId: 52, name_bn: 'মোগলাবাজার', name_en: 'Moglabazar' },
  { districtId: 52, name_bn: 'শাহপরান', name_en: 'Shah Paran' },
  { districtId: 52, name_bn: 'কানাইঘাট', name_en: 'Kanaighat' },
  { districtId: 52, name_bn: 'কোম্পানীগঞ্জ', name_en: 'Companiganj' },
  { districtId: 52, name_bn: 'গোয়াইনঘাট', name_en: 'Gowainghat' },
  { districtId: 52, name_bn: 'গোলাপগঞ্জ', name_en: 'Golapganj' },
  { districtId: 52, name_bn: 'জকিগঞ্জ', name_en: 'Zakiganj' },
  { districtId: 52, name_bn: 'জৈন্তাপুর', name_en: 'Jaintiapur' },
  { districtId: 52, name_bn: 'দক্ষিণ সুরমা', name_en: 'Dakshin Surma' },
  { districtId: 52, name_bn: 'ফেঞ্চুগঞ্জ', name_en: 'Fenchuganj' },
  { districtId: 52, name_bn: 'বালাগঞ্জ', name_en: 'Balaganj' },
  { districtId: 52, name_bn: 'বিয়ানীবাজার', name_en: 'Beanibazar' },
  { districtId: 52, name_bn: 'বিশ্বনাথ', name_en: 'Bishwanath' },
  // Sylhet Division End

  // Rangpur Division Start
  // Kurigram
  { districtId: 53, name_bn: 'উলিপুর', name_en: 'ULIPUR' },
  { districtId: 53, name_bn: 'কুড়িগ্রাম সদর', name_en: 'KURIGRAM SADAR' },
  { districtId: 53, name_bn: 'চর রাজিবপুর', name_en: 'CHAR RAJIBPUR' },
  { districtId: 53, name_bn: 'চিলমারী', name_en: 'CHILMARI' },
  { districtId: 53, name_bn: 'নাগেশ্বরী', name_en: 'NAGESHWARI' },
  { districtId: 53, name_bn: 'ফুলবাড়ী', name_en: 'PHULBARI' },
  { districtId: 53, name_bn: 'ভুরুঙ্গামারী', name_en: 'BHURUNGAMARI' },
  { districtId: 53, name_bn: 'রাজারহাট', name_en: 'RAJARHAT' },
  { districtId: 53, name_bn: 'রৌমারী', name_en: 'RAUMARI' },
  // Rangpur
  { districtId: 54, name_bn: 'কাউনিয়া', name_en: 'Kaunia' },
  { districtId: 54, name_bn: 'গঙ্গাচড়া', name_en: 'Gangachara' },
  { districtId: 54, name_bn: 'তারাগঞ্জ', name_en: 'Taraganj' },
  { districtId: 54, name_bn: 'পীরগঞ্জ', name_en: 'Pirganj' },
  { districtId: 54, name_bn: 'পীরগাছা', name_en: 'Pirgachha' },
  { districtId: 54, name_bn: 'বদরগঞ্জ', name_en: 'Badarganj' },
  { districtId: 54, name_bn: 'মিঠাপুকুর', name_en: 'Mitha Pukur' },
  { districtId: 54, name_bn: 'রংপুর সদর', name_en: 'Rangpur Sadar' },
  // Lalmonirhat
  { districtId: 55, name_bn: 'আদিতমারী', name_en: 'Aditmari' },
  { districtId: 55, name_bn: 'কালীগঞ্জ', name_en: 'Kaliganj' },
  { districtId: 55, name_bn: 'পাটগ্রাম', name_en: 'Patgram' },
  { districtId: 55, name_bn: 'লালমনিরহাট সদর', name_en: 'Lalmonirhat Sadar' },
  { districtId: 55, name_bn: 'হাতীবান্ধা', name_en: 'Hatibandha' },
  // Gaibandha
  { districtId: 56, name_bn: 'গাইবান্ধা সদর', name_en: 'Gaibandha Sadar' },
  { districtId: 56, name_bn: 'গোবিন্দগঞ্জ', name_en: 'Gobindaganj' },
  { districtId: 56, name_bn: 'পলাশবাড়ী', name_en: 'Palashbari' },
  { districtId: 56, name_bn: 'ফুলছড়ি', name_en: 'Fulchhari' },
  { districtId: 56, name_bn: 'সাঘাটা', name_en: 'Saghatta' },
  { districtId: 56, name_bn: 'সাদুল্লাপুর', name_en: 'Sadullapur' },
  { districtId: 56, name_bn: 'সুন্দরগঞ্জ', name_en: 'Sundarganj' },
  // Dinajpur
  { districtId: 57, name_bn: 'কাহারোল', name_en: 'Kaharole' },
  { districtId: 57, name_bn: 'খানসামা', name_en: 'Khansama' },
  { districtId: 57, name_bn: 'ঘোড়াঘাট', name_en: 'Ghoraghat' },
  { districtId: 57, name_bn: 'চিরিরবন্দর', name_en: 'Chirirbandar' },
  { districtId: 57, name_bn: 'দিনাজপুর সদর', name_en: 'Dinajpur Sadar' },
  { districtId: 57, name_bn: 'নবাবগঞ্জ', name_en: 'Nawabganj' },
  { districtId: 57, name_bn: 'পার্বতীপুর', name_en: 'Parbatipur' },
  { districtId: 57, name_bn: 'ফুলবাড়ী', name_en: 'Fulbari' },
  { districtId: 57, name_bn: 'বিরল', name_en: 'Biral' },
  { districtId: 57, name_bn: 'বিরামপুর', name_en: 'Birampur' },
  { districtId: 57, name_bn: 'বীরগঞ্জ', name_en: 'Birganj' },
  { districtId: 57, name_bn: 'বোচাগঞ্জ', name_en: 'Bochaganj' },
  { districtId: 57, name_bn: 'হাকিমপুর', name_en: 'Hakimpur' },
  // Panchagarh
  { districtId: 58, name_bn: 'আটোয়ারী', name_en: 'Atwari' },
  { districtId: 58, name_bn: 'তেঁতুলিয়া', name_en: 'Tentulia' },
  { districtId: 58, name_bn: 'দেবীগঞ্জ', name_en: 'Debiganj' },
  { districtId: 58, name_bn: 'পঞ্চগড় সদর', name_en: 'Panchagarh Sadar' },
  { districtId: 58, name_bn: 'বোদা', name_en: 'Boda' },
  //Thakurgaon
  { districtId: 59, name_bn: 'ঠাকুরগাঁও সদর', name_en: 'Thakurgaon Sadar' },
  { districtId: 59, name_bn: 'পীরগঞ্জ', name_en: 'Pirganj' },
  { districtId: 59, name_bn: 'বালিয়াডাঙ্গি', name_en: 'Baliadangi' },
  { districtId: 59, name_bn: 'রানীশংকাইল', name_en: 'Ranisankail' },
  { districtId: 59, name_bn: 'হরিপুর', name_en: 'Haripur' },
  // Nilphamari
  { districtId: 60, name_bn: 'কিশোরগঞ্জ', name_en: 'Kishoreganj' },
  { districtId: 60, name_bn: 'জলঢাকা', name_en: 'Jaldhaka' },
  { districtId: 60, name_bn: 'ডিমলা', name_en: 'Dimla' },
  { districtId: 60, name_bn: 'ডোমার', name_en: 'Domar' },
  { districtId: 60, name_bn: 'নীলফামারী সদর', name_en: 'Nilphamari Sadar' },
  { districtId: 60, name_bn: 'সৈয়দপুর', name_en: 'Saidpur' },
  // Rangpur Division End

  // Mymensingh Division Start
  // Mymensingh
  { districtId: 61, name_bn: 'ঈশ্বরগঞ্জ', name_en: 'Ishwarganj' },
  { districtId: 61, name_bn: 'গফরগাঁও', name_en: 'Gaffargaon' },
  { districtId: 61, name_bn: 'পাগলা', name_en: 'Pagla' },
  { districtId: 61, name_bn: 'গৌরীপুর', name_en: 'Gauripur' },
  { districtId: 61, name_bn: 'তারাকান্দা', name_en: 'Tarakanda' },
  { districtId: 61, name_bn: 'ত্রিশাল', name_en: 'Trishal' },
  { districtId: 61, name_bn: 'ধোবাউড়া', name_en: 'Dhobaura' },
  { districtId: 61, name_bn: 'নান্দাইল', name_en: 'Nandail' },
  { districtId: 61, name_bn: 'ফুলপুর', name_en: 'Phulpur' },
  { districtId: 61, name_bn: 'ফুলবাড়িয়া', name_en: 'Fulbaria' },
  { districtId: 61, name_bn: 'ভালুকা', name_en: 'Bhaluka' },
  { districtId: 61, name_bn: 'ময়মনসিংহ সদর', name_en: 'Mymensingh Sadar' },
  { districtId: 61, name_bn: 'মুক্তাগাছা', name_en: 'Muktagachha' },
  { districtId: 61, name_bn: 'হালুয়াঘাট', name_en: 'Haluaghat' },
  // Jamalpur
  { districtId: 62, name_bn: 'ইসলামপুর', name_en: 'Islampur' },
  { districtId: 62, name_bn: 'জামালপুর সদর', name_en: 'Jamalpur Sadar' },
  { districtId: 62, name_bn: 'দেওয়ানগঞ্জ', name_en: 'Dewanganj' },
  { districtId: 62, name_bn: 'বকশীগঞ্জ', name_en: 'Bakshiganj' },
  { districtId: 62, name_bn: 'মাদারগঞ্জ', name_en: 'Madarganj' },
  { districtId: 62, name_bn: 'মেলান্দহ', name_en: 'Melandaha' },
  { districtId: 62, name_bn: 'সরিষাবাড়ী', name_en: 'Sarishabari' },
  // Netrokona
  { districtId: 63, name_bn: 'নেত্রকোনা সদর', name_en: 'Netrokona Sadar' },
  { districtId: 63, name_bn: 'কেন্দুয়া', name_en: 'Kendua' },
  { districtId: 63, name_bn: 'বারহাট্টা', name_en: 'Barhatta' },
  { districtId: 63, name_bn: 'আটপাড়া', name_en: 'Atpara' },
  { districtId: 63, name_bn: 'মোহনগঞ্জ', name_en: 'Mohanganj' },
  { districtId: 63, name_bn: 'কলমাকান্দা', name_en: 'Kalmakanda' },
  { districtId: 63, name_bn: 'দুর্গাপুর', name_en: 'Durgapur' },
  { districtId: 63, name_bn: 'পূর্বধলা', name_en: 'Purbadhala' },
  { districtId: 63, name_bn: 'মদন', name_en: 'Madan' },
  { districtId: 63, name_bn: 'খালিয়াজুরী', name_en: 'Khaliajuri' },
  // Sherpur
  { districtId: 64, name_bn: 'ঝিনাইগাতী', name_en: 'Jhenaigati' },
  { districtId: 64, name_bn: 'নকলা', name_en: 'Nakla' },
  { districtId: 64, name_bn: 'নালিতাবাড়ী', name_en: 'Nalitabari' },
  { districtId: 64, name_bn: 'শেরপুর সদর', name_en: 'Sherpur Sadar' },
  { districtId: 64, name_bn: 'শ্রীবর্দী', name_en: 'Sreebardi' },
];
